import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 md:p-12 text-gray-200 mt-16">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="text-sm text-gray-600 mb-8">Last updated: November 27, 2024</p>

      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your
        information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>

      <p className="mb-8">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
        and use of information in accordance with this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Interpretation and Definitions</h2>
      <h3 className="text-xl font-medium mb-2">Interpretation</h3>
      <p className="mb-4">
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The
        following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3 className="text-xl font-medium mb-2">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside space-y-2 mb-8">
        <li>
          <strong>Account:</strong> means a unique account created for You to access our Service or parts of our
          Service.
        </li>
        <li>
          <strong>Affiliate:</strong> means an entity that controls, is controlled by, or is under common control with a
          party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities
          entitled to vote for election of directors or other managing authority.
        </li>
        <li>
          <strong>Company:</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers
          to laestellita.
        </li>
        <li>
          <strong>Cookies:</strong> are small files that are placed on Your computer, mobile device, or any other device
          by a website, containing the details of Your browsing history on that website among its many uses.
        </li>
        <li>
          <strong>Country:</strong> refers to: Philippines.
        </li>
        <li>
          <strong>Device:</strong> means any device that can access the Service such as a computer, a cellphone, or a
          digital tablet.
        </li>
        <li>
          <strong>Personal Data:</strong> is any information that relates to an identified or identifiable individual.
        </li>
        <li>
          <strong>Service:</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider:</strong> means any natural or legal person who processes the data on behalf of the
          Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service,
          to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the
          Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Usage Data:</strong> refers to data collected automatically, either generated by the use of the
          Service or from the Service infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website:</strong> refers to laestellita, accessible from{' '}
          <a
            href="https://laestellita.shop/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 underline"
          >
            https://laestellita.shop/
          </a>
          .
        </li>
        <li>
          <strong>You:</strong> means the individual accessing or using the Service, or the company, or other legal
          entity on behalf of which such individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
      <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul className="list-disc list-inside space-y-2">
        <li>
          By email:{' '}
          <a href="mailto:laestelitacateringservices@gmail.com" className="text-blue-600 underline">
          laestelitacateringservices@gmail.com
          </a>
        </li>
        <li>By phone number: (032) 272 8528</li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;
